"""
database.py — SQLite async database setup via SQLAlchemy
"""
import json
from datetime import datetime
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase, mapped_column, Mapped
from sqlalchemy import Index, Text, String, DateTime, ForeignKey, Integer, func
from typing import Optional

from config import settings

engine = create_async_engine(settings.database_url, echo=False)
AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    email: Mapped[str] = mapped_column(String, unique=True, index=True, nullable=False)
    password_hash: Mapped[str] = mapped_column(String, nullable=False)
    full_name: Mapped[str] = mapped_column(String, nullable=False)
    role: Mapped[str] = mapped_column(String, nullable=False)  # "doctor" | "patient"


class ConsultationSession(Base):
    __tablename__ = "consultation_sessions"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    doctor_id: Mapped[Optional[str]] = mapped_column(
        String, ForeignKey("users.id"), nullable=True, index=True
    )
    doctor_name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    patient_identifier: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    patient_name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    raw_transcript: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    labeled_transcript: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON
    extracted_entities: Mapped[Optional[str]] = mapped_column(Text, nullable=True)   # JSON
    soap_note: Mapped[Optional[str]] = mapped_column(Text, nullable=True)             # JSON
    soap_pdf_path: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    soap_pdf_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    status: Mapped[str] = mapped_column(String, default="in_progress")


class ChatbotSession(Base):
    """Persistent transcript for the website chatbot widget.

    Each visitor browser keeps a session_id in sessionStorage and replays it
    on every turn. The full conversation is stored as JSON on `messages` so
    we don't need a per-message child table for what is essentially append-only.
    """
    __tablename__ = "chatbot_sessions"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now()
    )
    user_id: Mapped[Optional[str]] = mapped_column(
        String, ForeignKey("users.id"), nullable=True, index=True
    )
    message_count: Mapped[int] = mapped_column(Integer, default=0)
    messages: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON list


class PatientAnalysisRecord(Base):
    __tablename__ = "patient_analyses"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    patient_id: Mapped[Optional[str]] = mapped_column(
        String, ForeignKey("users.id"), nullable=True, index=True
    )
    file_name: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    file_type: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    uploaded_file_path: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    uploaded_file_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    raw_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    findings: Mapped[Optional[str]] = mapped_column(Text, nullable=True)       # JSON
    summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    specialists: Mapped[Optional[str]] = mapped_column(Text, nullable=True)    # JSON
    urgency: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    diet_plan: Mapped[Optional[str]] = mapped_column(Text, nullable=True)      # JSON
    exercise_plan: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON
    precautions: Mapped[Optional[str]] = mapped_column(Text, nullable=True)    # JSON
    generated_pdf_path: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    generated_pdf_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)


class PatientChatSession(Base):
    """A single chat session between a patient and Dr. MediSense.

    A `session_summary` paragraph is generated by the LLM after every 10
    messages and again when the session is explicitly ended, so future
    sessions can replay a compact memory of past conversations.
    """
    __tablename__ = "patient_chat_sessions"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    patient_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id"), nullable=False, index=True
    )
    started_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    ended_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    # Short, human-readable title — auto-set from the first user turn so the
    # sidebar can show something more meaningful than "Apr 28, 5:16 PM" before
    # the agent has produced a summary.
    title: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    session_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    message_count: Mapped[int] = mapped_column(Integer, default=0)
    last_summary_at_count: Mapped[int] = mapped_column(Integer, default=0)

    __table_args__ = (
        Index("ix_patient_chat_sessions_patient_started", "patient_id", "started_at"),
    )


class PatientChatMessage(Base):
    """One message in a patient chat session (user or assistant).

    `message_metadata` is an opaque JSON column used for any extracted
    medical entities (symptoms, conditions, medications) we want to keep
    alongside the raw text for later analytics.
    """
    __tablename__ = "patient_chat_messages"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    session_id: Mapped[str] = mapped_column(
        String, ForeignKey("patient_chat_sessions.id"), nullable=False, index=True
    )
    patient_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id"), nullable=False, index=True
    )
    role: Mapped[str] = mapped_column(String, nullable=False)  # "user" | "assistant"
    content: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    message_metadata: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON
    # JSON list of {filename, mime_type, size_bytes, kind: "image"|"pdf"} entries
    # describing files the patient attached on this turn. Raw bytes are not stored.
    file_references: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_patient_chat_messages_session_created", "session_id", "created_at"),
        Index("ix_patient_chat_messages_patient_created", "patient_id", "created_at"),
    )


class PatientChatAudit(Base):
    """Append-only audit trail for every patient-chat API access."""
    __tablename__ = "patient_chat_audit"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    patient_id: Mapped[str] = mapped_column(
        String, ForeignKey("users.id"), nullable=False, index=True
    )
    action: Mapped[str] = mapped_column(String, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
    ip_address: Mapped[Optional[str]] = mapped_column(String, nullable=True)
    detail: Mapped[Optional[str]] = mapped_column(String, nullable=True)


async def init_db():
    """Create all tables on startup, and add newly introduced columns to
    pre-existing tables. SQLite won't ALTER an existing table via create_all,
    so we issue idempotent ADD COLUMN statements for the schema upgrade."""
    from sqlalchemy import text

    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

        new_columns = {
            "consultation_sessions": [
                ("doctor_id", "VARCHAR"),
                ("patient_name", "VARCHAR"),
                ("soap_pdf_path", "VARCHAR"),
                ("soap_pdf_size", "INTEGER"),
            ],
            "patient_analyses": [
                ("patient_id", "VARCHAR"),
                ("uploaded_file_path", "VARCHAR"),
                ("uploaded_file_size", "INTEGER"),
                ("generated_pdf_path", "VARCHAR"),
                ("generated_pdf_size", "INTEGER"),
            ],
            "chatbot_sessions": [
                ("user_id", "VARCHAR"),
                ("message_count", "INTEGER DEFAULT 0"),
            ],
            "patient_chat_messages": [
                ("file_references", "TEXT"),
            ],
            "patient_chat_sessions": [
                ("title", "VARCHAR"),
            ],
        }

        for table, cols in new_columns.items():
            existing_cols_result = await conn.execute(text(f"PRAGMA table_info({table})"))
            existing_cols = {row[1] for row in existing_cols_result.fetchall()}
            for col_name, col_type in cols:
                if col_name not in existing_cols:
                    await conn.execute(
                        text(f"ALTER TABLE {table} ADD COLUMN {col_name} {col_type}")
                    )


async def get_db():
    """FastAPI dependency — yields an async DB session."""
    async with AsyncSessionLocal() as session:
        yield session
